name: package_info_plus
description: Flutter plugin for querying information about the application package, such as CFBundleVersion on iOS or versionCode on Android.
version: 3.0.1
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/
issue_tracker: https://github.com/fluttercommunity/plus_plugins/labels/package_info_plus

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.packageinfo
        pluginClass: PackageInfoPlugin
      ios:
        pluginClass: FLTPackageInfoPlusPlugin
      linux:
        dartPluginClass: PackageInfoPlusLinuxPlugin
      macos:
        pluginClass: FLTPackageInfoPlusPlugin
      web:
        pluginClass: PackageInfoPlusWebPlugin
        fileName: src/package_info_plus_web.dart
      windows:
        dartPluginClass: PackageInfoPlusWindowsPlugin

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^0.13.0
  meta: ^1.3.0
  path: ^1.8.0
  package_info_plus_platform_interface: ^2.0.1
  win32: ">=2.7.0 <5.0.0"

dev_dependencies:
  build_runner: ^2.0.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.0.7
  test: ^1.21.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.11.0"
